[project]
name = "hse-ai"
version = "0.1.0"
description = "HSE AI Coursework and Homeworks"
readme = "README.md"
requires-python = ">=3.13, <3.14"
dependencies = [
    "matplotlib>=3.8.0",
    "nbformat>=5.9.0",
    "numba>=0.60.0",
    "numpy>=2.0.0",
    "pandas>=2.2.0",
    "plotly>=5.20.0",
    "seaborn>=0.13.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
